### ISSUE TITLE
Changing the orientation of the tree

### ISSUE THREAD

**Issue by Sammyskills** [deltoss/d3-mitch-tree#1]
Hi,

I must commend the great effort you've put in to this project. It is really awesome.

Please I will like to know if it is possible to change the orientation of the tree, let's say from top to bottom or any other, instead of the default left to right.

Thanks.

**Comment by deltoss** [comment]
Thanks Sammy for raising the first issue for this repository!

It's not possible at the moment, but it's a good idea for improvement. I'm mid-way making the changes for it now to incorporate an `orientation` setting.

**Comment by deltoss** [comment]
Added the 'orientation' option to the master branch.

**Comment by Sammyskills** [comment]
Thanks for this addition.
