### ISSUE TITLE
Is there a way to use this library with React?

### ISSUE THREAD

**Issue by shovelend** [deltoss/d3-mitch-tree#12]
This package is really appealing and we'd like to know if there's a way to integrate it with React components. Since it needs an element to be passed I tried to create a ref in React, but I'm getting various errors like:

```
TypeError: Cannot read property '__zoom' of null
Pi [as zoomTransform]
node_modules/d3-mitch-tree/lib/d3-mitch-tree.js:3221
  3218 | var zi = new Ni(1, 0, 0);
  3219 | 
  3220 | function Pi(t) {
> 3221 |   return t.__zoom || zi;
       | ^  3222 | }
  3223 | 
  3224 | function ji() {
```

Could you help us out here on how to use this library with React?

**Comment by danieladacruz** [comment]
@shovelend Where you able to use it with React? I am facing the same issue! thanks

**Comment by deltoss** [comment]
You can get it to work with React. See below sandbox:
https://codesandbox.io/s/mitch-d3-tree-react-basic-example-kjbxi
