### ISSUE TITLE
Is there a way to prevent auto collapsing when a node is selected?

### ISSUE THREAD

**Issue by saydmateen** [deltoss/d3-mitch-tree#14]
I saw the example where it shows how to expand all the nodes when you load the tree structure but when one is selected it then collapses the child's nodes, is there a way just to keep it open indefinitely.

**Comment by deltoss** [comment]
You can use the `nodeClick` event. Set the event argument's `continue` property to false to cancel the operation when the event type is a collapse.

For example:
```javascript
   var treePlugin = new d3.mitchTree.boxedTree()
     // ...
     .on("nodeClick", function(event) {
       if (event.type == 'collapse')
         event.continue = false;
     })
     .initialize();
```

For more information, see:
- the [Node Click Event Example](https://github.com/deltoss/d3-mitch-tree/blob/master/examples/Advanced%20Example%20with%20Node%20Click%20Event.html)
- https://github.com/deltoss/d3-mitch-tree/issues/7

**Comment by saydmateen** [comment]
I guess this may be a separate issue then because my nodeclick event never creates an even.type == 'collapse', it's always event.type == 'focus'. I attached how I have it configured, maybe I have some misconfiguration? 

[Example.txt](https://github.com/deltoss/d3-mitch-tree/files/3866352/Example.txt)

**Comment by deltoss** [comment]
You also need to disable `allowFocus`, so instead of:
```
//...
.setAllowFocus(true)
//...
```

You need to use:

```
//...
.setAllowFocus(false)
//...
```

**Comment by saydmateen** [comment]
That worked but now the node is not being shown as selected. Is there a way to stop collapse and to show the node as selected?

**Comment by deltoss** [comment]
I would probably make a fix eventually to select the node by default.
But for the time being, you can simply programmatically select & center the clicked node:

```javascript
 vm.treePlugin = new d3.mitchTree.boxedTree()
	.setIsFlatData(true)
	.setData(vm.service.treeSelected)
	.setAllowFocus(false)
	.setAllowZoom(false)
	.setAllowPan(true)
	.setAllowNodeCentering(true)
	.setElement(document.getElementById("tree-container"))
	.setIdAccessor(function (data) {
		return data.nodeId;
	})
	.setParentIdAccessor(function (data) {
		return data.parentId;
	})
	.setBodyDisplayTextAccessor(function (data) {
		return data.name;
	})
	.setMinScale(0)
	.on("nodeClick", function (event) {
                this.removeSelection(this.getRoot());
                event.nodeDataItem.selected = true;
                this.centerNode(event.nodeDataItem);

                // Cancel the collapse event
                if (event.type === 'collapse')
                    event.continue = false;
	})
	.initialize();
```

**Comment by saydmateen** [comment]
Your solution works great. Thanks!
