### ISSUE TITLE
d3-mitch-tree (box tree)  padding between two childern

### ISSUE THREAD

**Issue by kushjoshi26** [deltoss/d3-mitch-tree#2]
is there any simple way for put extra padding between child nodes(boxes) or leaf nodes.

**Comment by deltoss** [comment]
If you want spacing between nodes, you can use the following:

```javascript
var treePlugin = new d3.mitchTree.boxedTree()
    ...
    .getNodeSettings()
        .setSizingMode('nodesize')
        .setVerticalSpacing(100)				
        .setHorizontalSpacing(50)
        .back()
    .initialize();
```

Note, I noticed horizontal spacing isn't working. Looking into it now.

**Comment by kushjoshi26** [comment]
we did horizontal spacing using .setNodeDepthMultiplier() that's work for me

**Comment by kushjoshi26** [comment]
is there anyway to change color of stroke or color of text based on condition ???

**Comment by deltoss** [comment]
You can change the color of stroke or text using CSS. For more information, refer to the default theme [SASS files](https://github.com/deltoss/d3-mitch-tree/tree/master/src/sass/components/themes/default).

If you need more advanced control, work is in progress to change the way events work and set up additional events to improve the flexibility of this plugin.
