### ISSUE TITLE
Q: Custom color each level, and all levels visible

### ISSUE THREAD

**Issue by phantomtnt** [deltoss/d3-mitch-tree#3]
How would be the  right approach with this plugin to give each leveldepth group a class so i can give custom style to the elements of each level, i've tried to do it with **d3.selectAll** but when i select the attribute class the elements gets the browser default so everything looks black.

And its possible to have all the levels visible on start?

**Comment by deltoss** [comment]
Yes, it's possible.

To have all levels visible on start:
```javascript
var treePlugin = new d3.mitchTree.boxedTree()
        .setAllowFocus(false)
	// ... And your other settings...
	.initialize();

// Expand all nodes
var nodes = treePlugin.getNodes();
nodes.forEach(function(node, index, arr) {
	treePlugin.expand(node);
});

// Manually call the update method to render visual changes
treePlugin.update(treePlugin.getRoot());
```

As for the custom class, eventually I plan to add a events for that, however, for now you can use this rather hacky approach, which overrides the object's `update` method to add your own set of classes:

```javascript
var treePlugin = new d3.mitchTree.boxedTree()
        .setAllowFocus(false)
	// ... And your other settings...
	.initialize();

function updateTreeClasses(treePlugin)
{
	treePlugin.getPanningContainer().selectAll("g.node")
		.attr("class", function(data, index, arr) { 
			var depthClass = "depth-" + data.depth;
			var existingClasses = this.getAttribute('class');
			if (!existingClasses)
				return depthClass;
			var hasDepthClassAlready = (' ' + existingClasses + ' ').indexOf(' ' + depthClass + ' ') > -1;
			if (hasDepthClassAlready)
				return existingClasses;
			return existingClasses + " " + depthClass;
		});
}

// Override the core update method,
// so it'd call our custom update method
treePlugin.update = function(nodeDataItem){
        // Call the original update method
	treePlugin.__proto__.update.call(this, nodeDataItem);
	updateTreeClasses(this);
}

updateTreeClasses(treePlugin);
```

**Comment by phantomtnt** [comment]
Thanks!!, it worked really well.

I have another question, i don't know if is okay to make it here. i need that when the page loads the layout don't get **zoomed** or fit, maybe reducing the initial zoom or set the **setMinScale** provided, because the treelayout gets really big initially and is needed only that the user apply zoom with the mousewheel with the **setAllowZoom**.

**Comment by deltoss** [comment]
Great to know.

As it's a seperate problem, please raise a seperate issue for that.
