### ISSUE TITLE
Set Initial layout zoom

### ISSUE THREAD

**Issue by phantomtnt** [deltoss/d3-mitch-tree#4]
I need that when the page loads the layout don't get zoomed or fit, maybe reducing the initial zoom or set the setMinScale provided, because the treelayout gets really big initially and is needed only that the user apply zoom with the mousewheel with the setAllowZoom.

Thanks!

**Comment by deltoss** [comment]
By default, the minimum zoom scale is 1. So first, set the minimum scale to whatever you'd like, or 0 for no set minimum zoom level.

```javascript
var treePlugin = new d3.mitchTree.boxedTree()
    ...
    .setMinScale(0.5)
    .initialize();
```

Afterwards, you can set the zoom level as you wish:
```javascript
treePlugin.getZoomListener().scaleTo(treePlugin.getSvg(), 0.5);
```

**Comment by phantomtnt** [comment]
Thanks, it worked as expected, but when i zoom in the layout, it jank back the the layout to the center position. is there any way to solve this?

**Comment by deltoss** [comment]
Can't reproduce this issue. Could you provide your code/settings.

**Comment by phantomtnt** [comment]
This is the code i have!, thanks

	
```
getRootOrdered(data, function(datum) {
    var treePlugin = new d3.mitchTree.boxedTree()
        .setAllowFocus(false)
        .setAllowZoom(true)
        .setAllowPan(true)
        .setNodeDepthMultiplier(400)
        .setHeightWithoutMargins(800)
        .setMinScale(Scale)
        .setAllowNodeCentering(true)
        .setIsFlatData(true)
        .setData(datum)
        .setElement(document.getElementById("viz"))
        .setIdAccessor(function(d) {
            return d.id;
        })
        .setParentIdAccessor(function(d) {
            return d.parentId;
        })
        .setBodyDisplayTextAccessor(function(d) {
            return d.description;
        })
        .setTitleDisplayTextAccessor(function(d) {
            return d.name;
        })
        .initialize();

    // Expandir todos los nodos
    var nodes = treePlugin.getNodes();
    nodes.forEach(function(node, index, arr) {
        treePlugin.expand(node);
    });

    treePlugin.update(treePlugin.getRoot());
    treePlugin.update = function(nodeDataItem) {
        this.__proto__.update.call(this, nodeDataItem);
        updateTreeClasses(this);
    }
    updateTreeClasses(treePlugin);

    treePlugin.getZoomListener()
        .scaleTo(treePlugin.getSvg(), Scale)

    treePlugin.getPanningContainer()
        .attr('transform', 'translate(0) scale(' + Scale + ')')

    window.Dtree = treePlugin;

});
```

**Comment by deltoss** [comment]
Looks like the problem is the below:
```javascript
    treePlugin.getPanningContainer()
        .attr('transform', 'translate(0) scale(' + Scale + ')')
```

The zoom api is used to handle the scaling and translations. So if you want to modify those, it'd need to be via the [D3 zoom API](https://github.com/d3/d3-zoom).

Thus, you should use the `translateTo` or `translateBy` method.

For example:
```javascript
    treePlugin.getZoomListener()
        .translateTo(treePlugin.getSvg(), treePlugin.getWidthWithoutMargins(), treePlugin.getHeightWithoutMargins() / 2);
```

**Comment by phantomtnt** [comment]
Thanks, it worked and it center the layout as expected, but still i was having problems, so i ended limiting the height of the ''svg.mitch-d3-tree" with css, and i didnt have to set the zoom. it worked pretty well!!
