### ISSUE TITLE
Request to add two features to the project

### ISSUE THREAD

**Issue by mrmmg** [deltoss/d3-mitch-tree#6]
Hello
I use your project to show my work to the employer
Please add two features to your project:
1. In the Felt Data model, there is the possibility of canceling the whole tree movement. (Cancel zoom mode)
2- When clicked on a node, open a special link (such as a website) instead of zooming in.
Sorry for English
Thanks

**Comment by deltoss** [comment]
1. See this [example](https://github.com/deltoss/d3-mitch-tree/blob/master/examples/Advanced%20Example%20with%20Node%20Click%20Event.html#L209) for more information. The relevant code is below:

   ```javascript
   var treePlugin = new d3.mitchTree.boxedTree()
     // ...
     .on("nodeClick", function(event) {
       // You use the below line to cancel the
       // focus/expand/collapse event
       event.continue = false;
     })
     .initialize();
   ```

2. You can cancel the node event, then simply set the `location.href`.
   ```javascript
   var treePlugin = new d3.mitchTree.boxedTree()
     // ...
     .on("nodeClick", function(event) {
       // You use the below line to cancel the
       // focus/expand/collapse event
       event.continue = false;
       location.href = "<YourURL>";
     })
     .initialize();
   ```

**Comment by mrmmg** [comment]
Thank you for your reply
What should I do if I want **to open a link by clicking on a special node?** **for example, by clicking on a node with id 1 opens** `https://google.com` **and by clicking on a node with id 2 opens** `https://yahoo.com`.
Thanks
