### ISSUE TITLE
How to open a link by clicking on a node with special id?

### ISSUE THREAD

**Issue by mrmmg** [deltoss/d3-mitch-tree#7]
According to issue #6 :
What should I do if I want to open a link by clicking on a special node? **for example, by clicking on a node with id 1 opens `https://google.com` and by clicking on a node with id 2 opens `https://yahoo.com`**
Thanks

**Comment by deltoss** [comment]
1. You can use the event object on node click. See this [example](https://github.com/deltoss/d3-mitch-tree/blob/master/examples/Advanced%20Example%20with%20Node%20Click%20Event.html#L209) for more information.

   ```javascript
   var treePlugin = new d3.mitchTree.boxedTree()
     // ...
     .on("nodeClick", function(event) {
       if (event.nodeDataItem.data.id == 1) {
           event.continue = false;
           location.href = "https://www.google.com";
       } else if (event.nodeDataItem.data.id == 2) {
           event.continue = false;
           location.href = "https://www.yahoo.com";
       }
     })
     .initialize();
   ```

Note it doesn't have to be strictly `id`. It can be anything which you provided as your data items.

**Comment by mrmmg** [comment]
Thanks a lot
