### ISSUE TITLE
Want to add image in D3 mitch tree node .

### ISSUE THREAD

**Issue by Almoeeni** [deltoss/d3-mitch-tree#9]
Hi Deltoss,
I want to add image in every node of that users. In json response i'm sending the path of image.
Is it possible to show image?

**Comment by deltoss** [comment]
Yes, it's possible, with the power of D3.

The solution can be similar to this post:
  https://github.com/deltoss/d3-mitch-tree/issues/3#issuecomment-478303986

But instead of changing the class attribute via `attr`, you'd probably want to use D3 `append`.
